/**
 * @typedef {Object} ScheduleEvent
 * @property {string} id
 * @property {string} title
 * @property {string} [course]
 * @property {'class'|'meeting'|'event'|'exam'|'office-hours'} type
 * @property {string} startTime
 * @property {string} endTime
 * @property {'Monday'|'Tuesday'|'Wednesday'|'Thursday'|'Friday'|'Saturday'|'Sunday'} day
 * @property {string} [location]
 * @property {string} [instructor]
 * @property {string} [description]
 * @property {string} [color]
 */
export const sampleStudentSchedule = [
  {
    id: '1',
    title: 'Computer Science 101',
    course: 'CS101',
    type: 'class',
    startTime: '09:00',
    endTime: '10:30',
    day: 'Monday',
    location: 'Room 204, Science Building',
    instructor: 'Dr. Smith',
    color: 'bg-blue-500',
  },
  {
    id: '2',
    title: 'Computer Science 101',
    course: 'CS101',
    type: 'class',
    startTime: '09:00',
    endTime: '10:30',
    day: 'Wednesday',
    location: 'Room 204, Science Building',
    instructor: 'Dr. Smith',
    color: 'bg-blue-500',
  },
  {
    id: '3',
    title: 'Mathematics 201',
    course: 'MATH201',
    type: 'class',
    startTime: '11:00',
    endTime: '12:30',
    day: 'Tuesday',
    location: 'Room 105, Math Building',
    instructor: 'Prof. Johnson',
    color: 'bg-green-500',
  },
  {
    id: '4',
    title: 'Mathematics 201',
    course: 'MATH201',
    type: 'class',
    startTime: '11:00',
    endTime: '12:30',
    day: 'Thursday',
    location: 'Room 105, Math Building',
    instructor: 'Prof. Johnson',
    color: 'bg-green-500',
  },
  {
    id: '5',
    title: 'English Literature',
    course: 'ENG301',
    type: 'class',
    startTime: '14:00',
    endTime: '15:30',
    day: 'Monday',
    location: 'Room 301, Arts Building',
    instructor: 'Dr. Williams',
    color: 'bg-purple-500',
  },
  {
    id: '6',
    title: 'English Literature',
    course: 'ENG301',
    type: 'class',
    startTime: '14:00',
    endTime: '15:30',
    day: 'Friday',
    location: 'Room 301, Arts Building',
    instructor: 'Dr. Williams',
    color: 'bg-purple-500',
  },
  {
    id: '7',
    title: 'Physics Lab',
    course: 'PHY102',
    type: 'class',
    startTime: '16:00',
    endTime: '18:00',
    day: 'Wednesday',
    location: 'Lab 3, Science Building',
    instructor: 'Dr. Brown',
    color: 'bg-orange-500',
  },
  {
    id: '8',
    title: 'Study Group',
    type: 'meeting',
    startTime: '13:00',
    endTime: '14:00',
    day: 'Thursday',
    location: 'Library, Room 203',
    color: 'bg-yellow-500',
  },
];
export const sampleFacultySchedule = [
  {
    id: '1',
    title: 'Teach CS101',
    course: 'CS101',
    type: 'class',
    startTime: '09:00',
    endTime: '10:30',
    day: 'Monday',
    location: 'Room 204, Science Building',
    color: 'bg-blue-500',
  },
  {
    id: '2',
    title: 'Teach CS101',
    course: 'CS101',
    type: 'class',
    startTime: '09:00',
    endTime: '10:30',
    day: 'Wednesday',
    location: 'Room 204, Science Building',
    color: 'bg-blue-500',
  },
  {
    id: '3',
    title: 'Office Hours',
    type: 'office-hours',
    startTime: '14:00',
    endTime: '16:00',
    day: 'Tuesday',
    location: 'Office 401, Science Building',
    description: 'Student consultations',
    color: 'bg-green-500',
  },
  {
    id: '4',
    title: 'Office Hours',
    type: 'office-hours',
    startTime: '14:00',
    endTime: '16:00',
    day: 'Thursday',
    location: 'Office 401, Science Building',
    description: 'Student consultations',
    color: 'bg-green-500',
  },
  {
    id: '5',
    title: 'Faculty Meeting',
    type: 'meeting',
    startTime: '10:00',
    endTime: '11:30',
    day: 'Friday',
    location: 'Conference Room A',
    color: 'bg-purple-500',
  },
  {
    id: '6',
    title: 'Research Time',
    type: 'event',
    startTime: '11:00',
    endTime: '13:00',
    day: 'Tuesday',
    location: 'Office 401',
    color: 'bg-teal-500',
  },
];
export const sampleAdminSchedule = [
  {
    id: '1',
    title: 'Department Heads Meeting',
    type: 'meeting',
    startTime: '09:00',
    endTime: '10:30',
    day: 'Monday',
    location: 'Admin Building, Conference Room',
    color: 'bg-red-500',
  },
  {
    id: '2',
    title: 'Budget Review',
    type: 'meeting',
    startTime: '11:00',
    endTime: '12:30',
    day: 'Tuesday',
    location: 'Admin Office 501',
    color: 'bg-orange-500',
  },
  {
    id: '3',
    title: 'Student Council Meeting',
    type: 'meeting',
    startTime: '14:00',
    endTime: '15:30',
    day: 'Wednesday',
    location: 'Student Center',
    color: 'bg-blue-500',
  },
  {
    id: '4',
    title: 'Campus Tour for Prospective Students',
    type: 'event',
    startTime: '10:00',
    endTime: '12:00',
    day: 'Thursday',
    location: 'Main Campus Entrance',
    color: 'bg-green-500',
  },
  {
    id: '5',
    title: 'Policy Review Session',
    type: 'meeting',
    startTime: '13:00',
    endTime: '15:00',
    day: 'Friday',
    location: 'Admin Building, Room 302',
    color: 'bg-purple-500',
  },
];
